# Generated by Django 3.0.3 on 2020-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('data_in', models.DateField(db_index=True)),
                ('data_out', models.DateField()),
                ('is_breakfast', models.BooleanField()),
            ],
        ),
    ]
