# Generated by Django 3.0.3 on 2020-02-18 12:46

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('data_in', models.DateField(db_index=True)),
                ('data_out', models.DateField()),
                ('is_breakfast', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(max_length=3)),
                ('type', models.CharField(choices=[('D', 'Одна двуспальная кровать'), ('S', 'Две односпальные кровати')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomsType',
        ),
        migrations.AddField(
            model_name='bookingorders',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Rooms'),
        ),
        migrations.AddField(
            model_name='bookingorders',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Clients'),
        ),
    ]
