# Generated by Django 3.0.3 on 2020-04-10 13:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_room_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'base_manager_name': 'active_objects'},
        ),
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
