# Generated by Django 3.0.3 on 2020-04-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_auto_20200410_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelManagers(
            name='room',
            managers=[
            ],
        ),
    ]
